Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - hwmon.gemspec

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false
